
export const INIT_ACCOUNT_LIST = 'INIT_ACCOUNT_LIST'//
export const INIT_FLOW_LIST = 'INIT_FLOW_LIST'//
export const INIT_REFLECT_LIST = 'INIT_REFLECT_LIST'//
export const INIT_AGENT_LIST = 'INIT_AGENT_LIST'//
export const INIT_ACTOR_SALARY_LIST = 'INIT_ACTOR_SALARY_LIST'//

export const INIT_UNION_SALARY_LIST = 'INIT_UNION_SALARY_LIST'//


