export const INIT_USER_INFO = 'INIT_USER_INFO'
export const GET_USER_MY_INFO = 'GET_USER_MY_INFO'
export const INIT_USER_AUTHORITIES = 'INIT_USER_AUTHORITIES'
export const INIT_SYSTEM_INFO = 'INIT_SYSTEM_INFO'

export const INIT_PLAT_INFO = 'INIT_PLAT_INFO'
export const INIT_UNION_INFO = 'INIT_UNION_INFO'
export const CLEAR_ANALYZE_INFO = 'CLEAR_ANALYZE_INFO'



export const CHANGE_MOBILE = 'CHANGE_MOBILE'

export const GET_USER_SETTING_INFO = 'GET_USER_SETTING_INFO'





