export const INIT_ACCOUNT_GROUP = 'INIT_ACCOUNT_GROUP'//
export const INIT_AUTHORITIES_LIST = 'INIT_AUTHORITIES_LIST'//
export const INIT_ACCOUNT_GROUP_DETAIL = 'INIT_ACCOUNT_GROUP_DETAIL'//



export const INIT_ACCOUNT_LIST = 'INIT_ACCOUNT_LIST'//




